import { chromium } from 'playwright';

const browser = await chromium.launch({
  executablePath: 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe',
  headless: false,
});
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 } });
const page = await ctx.newPage();

await page.goto('http://localhost:5173');
await page.waitForSelector('.app-container', { timeout: 10000 });
await page.waitForTimeout(1000);

console.log('\n======================================================');
console.log('⚡ 1. TEST DE WIDGETS DINÁMICOS DISPARADOS POR CRISTI AI');
console.log('======================================================');

// Trigger dynamic widgets via window.__cristiEventBus
await page.evaluate(() => {
  if (window.__cristiEventBus) {
    // 1. Weather Widget generated by Cristi
    window.__cristiEventBus.emit('widget_triggered', {
      id: 'weather-01',
      type: 'weather',
      title: 'Clima: Ciudad de México',
      content: '24°C • Soleado y agradable • Viento 10 km/h',
      time: '12:00',
      duration: 30000
    });

    // 2. Reminder generated by Cristi
    window.__cristiEventBus.emit('widget_triggered', {
      id: 'reminder-01',
      type: 'reminder',
      title: 'Revisión con Cristi AI',
      content: 'Completar módulos de visión y optimizar shader Live2D',
      time: '18:30',
      tag: 'Urgente',
      done: false
    });

    // 3. Alarm generated by Cristi
    window.__cristiEventBus.emit('widget_triggered', {
      id: 'alarm-01',
      type: 'alarm',
      title: 'Alarma: Sesión de Enfoque',
      time: '20:00',
      tag: 'Alarma'
    });
  }
});

await page.waitForTimeout(1000);

const dynamicWidgets = await page.evaluate(() => {
  const cards = Array.from(document.querySelectorAll('.cristi-widget-card'));
  return cards.map(c => ({
    title: c.querySelector('.cristi-widget-title')?.innerText,
    content: c.querySelector('.cristi-widget-content')?.innerText,
    time: c.querySelector('.cristi-widget-time')?.innerText,
    tag: c.querySelector('.cristi-widget-tag')?.innerText
  }));
});

console.log('  Widgets de Cristi AI renderizados:', dynamicWidgets);
await page.screenshot({ path: 'C:/Users/jerem/.gemini/antigravity-ide/brain/428cbd8d-9fd9-4bb5-b96a-e16db84be0cb/widgets_cristi_dynamic.png' });

console.log('\n======================================================');
console.log('📋 2. TEST DE MENÚ CONTEXTUAL ULTRA-MINIMALISTA & RESPONSIVO');
console.log('======================================================');

// Open Context Menu via Right Click on live2d canvas
await page.mouse.click(640, 360, { button: 'right' });
await page.waitForTimeout(800);

const menuStats = await page.evaluate(() => {
  const menu = document.querySelector('.custom-context-menu');
  const items = Array.from(document.querySelectorAll('.context-menu-item'));
  return {
    isOpen: !!menu,
    width: menu ? window.getComputedStyle(menu).width : null,
    maxHeight: menu ? window.getComputedStyle(menu).maxHeight : null,
    overflowY: menu ? window.getComputedStyle(menu).overflowY : null,
    itemCount: items.length,
    itemsText: items.map(i => i.innerText.split('\n')[0])
  };
});

console.log('  Menú Contextual Minimalista Stats:', menuStats);
await page.screenshot({ path: 'C:/Users/jerem/.gemini/antigravity-ide/brain/428cbd8d-9fd9-4bb5-b96a-e16db84be0cb/context_menu_minimalist.png' });

console.log('\n======================================================');
console.log('🔒 3. TEST DE WIDGET DE PANTALLA DE BLOQUEO (WIN 11)');
console.log('======================================================');

// Click on Lock Screen Mode in context menu
await page.evaluate(() => {
  const items = Array.from(document.querySelectorAll('.context-menu-item'));
  const lockItem = items.find(i => i.innerText.includes('Pantalla de Bloqueo') || i.innerText.includes('Bloqueo'));
  if (lockItem) lockItem.click();
});

await page.waitForTimeout(1000);

const lockWidgetStats = await page.evaluate(() => {
  const overlay = document.querySelector('.lockscreen-overlay-container');
  const card = document.querySelector('.lockscreen-tactical-card');
  const clock = document.querySelector('.lockscreen-time')?.innerText;
  const presence = document.querySelector('.lockscreen-presence-text')?.innerText;
  return {
    isOpen: !!overlay,
    clock,
    presence
  };
});

console.log('  Widget Pantalla de Bloqueo Win11:', lockWidgetStats);
await page.screenshot({ path: 'C:/Users/jerem/.gemini/antigravity-ide/brain/428cbd8d-9fd9-4bb5-b96a-e16db84be0cb/lockscreen_widget_live.png' });

await browser.close();
console.log('\n✨ TODOS LOS TESTS COMPLETADOS SATISFACTORIAMENTE!');
