import React, { useState, useEffect, useRef } from 'react';
import {
  Bell,
  Clock,
  CloudSun,
  CheckCircle2,
  Sparkles,
  X,
  Pin,
  Calendar,
  AlertCircle
} from 'lucide-react';
import { eventBus, EVENTS } from '../services/eventBus';
import { useClickThrough } from '../hooks/useClickThrough';

const STORAGE_KEY_CRISTI_WIDGETS = 'cristi_ai_active_widgets';

/**
 * Cristi AI - Dynamic Tactical Widgets
 * Minimalist, event-driven widgets triggered exclusively by Cristi AI.
 * Zero generic placeholders: only renders when Cristi generates an alarm,
 * reminder, weather update, or tactical note.
 */
export function DesktopWidgets({ isVisible = true }) {
  const containerRef = useRef(null);
  const [widgets, setWidgets] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_CRISTI_WIDGETS);
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  // Listen to Cristi AI widget events
  useEffect(() => {
    const handleWidgetTriggered = (widget) => {
      if (!widget || !widget.id) return;
      setWidgets((prev) => {
        const filtered = prev.filter((w) => w.id !== widget.id);
        const updated = [widget, ...filtered];
        localStorage.setItem(STORAGE_KEY_CRISTI_WIDGETS, JSON.stringify(updated));
        return updated;
      });

      // If widget has a temporary auto-dismiss duration
      if (widget.duration && widget.duration > 0) {
        setTimeout(() => {
          handleDismiss(widget.id);
        }, widget.duration);
      }
    };

    const handleWidgetDismissed = ({ id }) => {
      if (id) handleDismiss(id);
    };

    const unsubTrigger = eventBus.on(EVENTS.WIDGET_TRIGGERED, handleWidgetTriggered);
    const unsubDismiss = eventBus.on(EVENTS.WIDGET_DISMISSED, handleWidgetDismissed);

    return () => {
      unsubTrigger();
      unsubDismiss();
    };
  }, []);

  const { interactiveProps } = useClickThrough();

  const handleDismiss = (id) => {
    setWidgets((prev) => {
      const updated = prev.filter((w) => w.id !== id);
      localStorage.setItem(STORAGE_KEY_CRISTI_WIDGETS, JSON.stringify(updated));
      return updated;
    });
  };

  const handleToggleDone = (id) => {
    setWidgets((prev) => {
      const updated = prev.map((w) => (w.id === id ? { ...w, done: !w.done } : w));
      localStorage.setItem(STORAGE_KEY_CRISTI_WIDGETS, JSON.stringify(updated));
      return updated;
    });
  };

  // Only render if there are active widgets generated by Cristi and isVisible is true
  if (!isVisible || widgets.length === 0) return null;

  return (
    <div ref={containerRef} className="cristi-widgets-viewport zen-fadeable-ui" {...interactiveProps}>
      {widgets.map((widget) => {
        let Icon = Sparkles;
        let iconColor = '#c084fc';
        if (widget.type === 'weather') {
          Icon = CloudSun;
          iconColor = '#f59e0b';
        } else if (widget.type === 'alarm') {
          Icon = Clock;
          iconColor = '#f43f5e';
        } else if (widget.type === 'reminder') {
          Icon = Bell;
          iconColor = '#a855f7';
        }

        return (
          <div
            key={widget.id}
            className={`cristi-widget-card ${widget.done ? 'done' : ''}`}
          >
            {/* Tech Corner Crosshairs */}
            <span className="hud-corner hud-corner-tl" />
            <span className="hud-corner hud-corner-tr" />
            <span className="hud-corner hud-corner-bl" />
            <span className="hud-corner hud-corner-br" />

            <div className="cristi-widget-icon-box" style={{ color: iconColor }}>
              <Icon size={12} />
            </div>

            <div className="cristi-widget-info">
              <div className="cristi-widget-header">
                <span className="cristi-widget-title">{widget.title}</span>
                {widget.time && (
                  <span className="cristi-widget-time">[{widget.time}]</span>
                )}
              </div>

              {widget.content && (
                <p className="cristi-widget-content">{widget.content}</p>
              )}

              {widget.tag && (
                <span className="cristi-widget-tag">#{widget.tag}</span>
              )}
            </div>

            <div className="cristi-widget-actions">
              {widget.type === 'reminder' && (
                <button
                  type="button"
                  className="cristi-widget-action-btn check"
                  onClick={() => handleToggleDone(widget.id)}
                  title={widget.done ? 'Pendiente' : 'Completado'}
                >
                  <CheckCircle2 size={11} className={widget.done ? 'checked' : ''} />
                </button>
              )}

              <button
                type="button"
                className="cristi-widget-action-btn dismiss"
                onClick={() => handleDismiss(widget.id)}
                title="Cerrar widget"
              >
                <X size={11} />
              </button>
            </div>

            {widget.duration && widget.duration > 0 && (
              <div
                className="cristi-widget-timer-bar"
                style={{ animationDuration: `${widget.duration}ms` }}
              />
            )}
          </div>
        );
      })}
    </div>
  );
}

export default DesktopWidgets;
