import React, { useState, useEffect, useRef } from 'react';
import {
  Bell,
  Clock,
  CloudSun,
  CheckCircle2,
  Sparkles,
  X
} from 'lucide-react';
import { eventBus, EVENTS } from '../infrastructure/events/eventBus.js';
import { proactiveScheduler } from '../domain/interaction/ProactiveScheduler.js';
import { useClickThrough } from '../hooks/useClickThrough.js';
import { useWidgetStore } from '../stores/useWidgetStore.js';
import { useCompanionStore } from '../stores/useCompanionStore.js';
import { Widget } from '@/types';

const STORAGE_KEY_CRISTI_WIDGETS = 'cristi_ai_widgets_data';

export interface DesktopWidgetsProps {
  isVisible?: boolean;
}

/**
 * Cristi AI - Dynamic Tactical Widgets
 * Minimalist, event-driven widgets triggered exclusively by Cristi AI.
 * Zero generic placeholders: only renders when Cristi generates an alarm,
 * reminder, weather update, or tactical note.
 */
export const DesktopWidgets: React.FC<DesktopWidgetsProps> = React.memo(function DesktopWidgets(props = {}) {
  const storeVisible = useWidgetStore((s) => s.showWidgets);
  const isUiVisible = useCompanionStore((s) => s.isUiVisible && !s.isZenMode);
  const isVisible = props.isVisible !== undefined ? props.isVisible : (storeVisible && isUiVisible);
  const containerRef = useRef<HTMLDivElement>(null);
  const [widgets, setWidgets] = useState<Widget[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_CRISTI_WIDGETS);
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  const autoDismissTimersRef = useRef<Set<ReturnType<typeof setTimeout>>>(new Set());

  // Listen to Cristi AI widget events
  useEffect(() => {
    const handleWidgetTriggered = (widget: Widget) => {
      if (!widget || !widget.id) return;
      setWidgets((prev) => {
        const filtered = prev.filter((w) => w.id !== widget.id);
        const updated = [widget, ...filtered];
        try {
          localStorage.setItem(STORAGE_KEY_CRISTI_WIDGETS, JSON.stringify(updated));
        } catch (_) {}
        return updated;
      });

      // If widget has a temporary auto-dismiss duration
      if (widget.duration && widget.duration > 0) {
        const timerId = setTimeout(() => {
          autoDismissTimersRef.current.delete(timerId);
          handleDismiss(widget.id);
        }, widget.duration);
        autoDismissTimersRef.current.add(timerId);
      }
    };

    const handleWidgetDismissed = ({ id }: { id?: string | number }) => {
      if (id) handleDismiss(String(id));
    };

    const unsubTrigger = eventBus.on(EVENTS.WIDGET_TRIGGERED, handleWidgetTriggered);
    const unsubDismiss = eventBus.on(EVENTS.WIDGET_DISMISSED, handleWidgetDismissed);

    return () => {
      unsubTrigger();
      unsubDismiss();
      for (const t of autoDismissTimersRef.current) {
        clearTimeout(t);
      }
      autoDismissTimersRef.current.clear();
    };
  }, []);

  const { interactiveProps } = useClickThrough();

  const handleDismiss = (id: string | number) => {
    const targetId = String(id);
    setWidgets((prev) => {
      const updated = prev.filter((w) => String(w.id) !== targetId);
      try {
        localStorage.setItem(STORAGE_KEY_CRISTI_WIDGETS, JSON.stringify(updated));
      } catch (_) {}
      return updated;
    });
    eventBus.emit(EVENTS.WIDGET_DISMISSED, { id: targetId });
    proactiveScheduler.cancelTask(targetId);
  };

  const handleToggleDone = (id: string | number) => {
    const targetId = String(id);
    setWidgets((prev) => {
      const updated = prev.map((w) => (String(w.id) === targetId ? { ...w, done: !w.done } : w));
      try {
        localStorage.setItem(STORAGE_KEY_CRISTI_WIDGETS, JSON.stringify(updated));
      } catch (_) {}
      return updated;
    });
  };

  // Only render if there are active widgets generated by Cristi and isVisible is true
  if (!isVisible || widgets.length === 0) return null;

  return (
    <div ref={containerRef} className="cristi-widgets-viewport zen-fadeable-ui pointer-events-auto" {...interactiveProps}>
      {widgets.map((widget) => {
        let Icon = Sparkles;
        let iconColor = '#c084fc';
        if (widget.type === 'weather') {
          Icon = CloudSun;
          iconColor = '#f59e0b';
        } else if (widget.type === 'alarm') {
          Icon = Clock;
          iconColor = '#f43f5e';
        } else if (widget.type === 'reminder') {
          Icon = Bell;
          iconColor = '#a855f7';
        }

        return (
          <div
            key={widget.id}
            className={`cristi-widget-card pointer-events-auto ${widget.done ? 'done' : ''}`}
          >
            {/* Tech Corner Crosshairs */}
            <span className="hidden" />
            <span className="hidden" />
            <span className="hidden" />
            <span className="hidden" />

            <div className="cristi-widget-icon-box" style={{ color: iconColor }}>
              <Icon size={12} />
            </div>

            <div className="cristi-widget-info">
              <div className="cristi-widget-header">
                <span className="cristi-widget-title">{widget.title}</span>
                {widget.time && (
                  <span className="cristi-widget-time">[{widget.time}]</span>
                )}
              </div>

              {widget.content && (
                <p className="cristi-widget-content">{widget.content}</p>
              )}

              {widget.tag && (
                <span className="cristi-widget-tag">#{widget.tag}</span>
              )}
            </div>

            <div className="cristi-widget-actions">
              {widget.type === 'reminder' && (
                <button
                  type="button"
                  className="cristi-widget-action-btn check"
                  onClick={(e) => {
                    e.stopPropagation();
                    e.preventDefault();
                    handleToggleDone(widget.id);
                  }}
                  onPointerDown={(e) => e.stopPropagation()}
                  title={widget.done ? 'Pendiente' : 'Completado'}
                  aria-label="Completar"
                >
                  <CheckCircle2 size={13} className={widget.done ? 'checked text-emerald-400' : ''} />
                </button>
              )}

              <button
                type="button"
                className="cristi-widget-action-btn dismiss"
                onClick={(e) => {
                  e.stopPropagation();
                  e.preventDefault();
                  handleDismiss(widget.id);
                }}
                onPointerDown={(e) => e.stopPropagation()}
                title="Descartar alarma o recordatorio"
                aria-label="Cerrar widget"
              >
                <X size={13} />
              </button>
            </div>

            {widget.duration && widget.duration > 0 && (
              <div
                className="cristi-widget-timer-bar"
                style={{ animationDuration: `${widget.duration}ms` }}
              />
            )}
          </div>
        );
      })}
    </div>
  );
});

export default DesktopWidgets;
